vlog ../interfaces/memory_interface.sv
vlog ../src/systolic_array_top.sv
vlog ../src/memory.sv
vlog ../src/async_fifo/*.sv
vlog ../src/memory_ctrl.sv
vlog ../src/row_converter.sv
vlog ../src/array_a_addresess_generator.sv
vlog ../src/array_b_addresses_generator.sv
vlog ../src/systolic_array_ctrl.sv
vlog ../src/mem_a_addresses_generator.sv
vlog ../src/mem_b_addresses_generator.sv
vlog ../src/mem_c_addresses_generator.sv
vlog ../src/buffer_write_address_generator.sv
vlog ../src/mult.sv
vlog ../src/add.sv
vlog ../src/mac.sv
vlog ../src/auto_shift_register.sv
vlog ../src/crossbar.sv
vlog ../src/systolic_array.sv
vlog ../src/array_results_controller.sv
vlog ../src/mem_bank_b_address_gen.sv
vlog ../src/data_sequencer.sv